### ISSUE TITLE
I can't find the download buttobt

### ISSUE THREAD

**Issue by HalFrgrd** [mabhishetty/CrawlerFirstRelease#1]
Where is it???

**Comment by mabhishetty** [comment]
Hi HalFrgrd,
Thanks for reaching out.
A good friend of mine told me about a 'git clone' command.
The syntax is: git clone <url>, where the url for this repository is: https://github.com/mabhishetty/CrawlerFirstRelease.
Here is a link to the documentation - you may find this helpful!
https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository
Thanks a lot
